### **Q1: Difference in Data Types of `list_` and `array_list`**
ANS: The `list_` is a Python list containing string elements, while `array_list` is a NumPy array that also holds string elements but as a NumPy array.

#### **Code to print the data types of both variables:**
```python
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
```

**Output:**
```
Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>
```

---

### **Q2: Data Type of Each Element in `list_` and `array_list`**
ANS: We can iterate over both variables and print the data type of each element.

#### **Code to print the data type of each element:**
```python
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))
```

**Output:**
```
Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
```


---

### **Q3: Effect of Changing `array_list` Data Type to `int`**
When we convert `array_list` elements to integers using `dtype=int`, it changes the element type.

#### **Modified Code to Print Data Types of Each Element**
```python
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("\nData types of elements in array_list after dtype=int:")
for item in array_list:
    print(type(item))
```

**Output:**
```
Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list after dtype=int:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
```
Now, the elements of `array_list` are converted to `numpy.int64`, while `list_` remains a list of strings.

---

### **Considering `num_list` and `num_array`**
Given:
```python
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
```
- `num_list` is a nested Python list.
- `num_array` is a NumPy array.

#### **To Check Their Data Types:**
```python
print("Data type of num_list:", type(num_list))
print("Data type of num_array:", type(num_array))
```

**Output:**
```
Data type of num_list: <class 'list'>
Data type of num_array: <class 'numpy.ndarray'>
```

#### **To Print Data Types of Each Element:**
```python
print("Data types of elements in num_list:")
for row in num_list:
    for item in row:
        print(type(item))

print("\nData types of elements in num_array:")
for row in num_array:
    for item in row:
        print(type(item))
```

**Output:**
```
Data types of elements in num_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in num_array:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
```
The elements in `num_list` are of type `int`, whereas in `num_array`, they are stored as `numpy.int64`.

---
### **Q4: Characteristics of `num_array`**  
Given:
```python
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
```
To find the **shape** and **size** of `num_array`:

#### **Code:**
```python
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)
```

#### **Output:**
```
Shape of num_array: (2, 3)
Size of num_array: 6
```
- `.shape` returns **(2,3)**, meaning 2 rows and 3 columns.
- `.size` returns **6**, which is the total number of elements.

---

### **Q5: Create a 3×3 Zero Matrix**  
We use `np.zeros()` to create a matrix filled with zeros.

#### **Code:**
```python
zero_matrix = np.zeros((3, 3))
print(zero_matrix)
```

#### **Output:**
```
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```
- A **3×3 matrix** is created with all elements **0**.

---

### **Q6: Create a 5×5 Identity Matrix**  

```python
import numpy as np

data1 = np.diag([1, 1, 1, 1, 1])
print(data1)
```

#### **Output:**
```
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
```

